#! /usr/bin/sudo /usr/bin/python2.7
import time
import math
import stm
import socket
import sys
import json

running = True
while running:
    print "start"
    connected = True
    server = socket.socket()
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) 
    server.bind(('0.0.0.0', 50001))
    server.listen(1)
    conn, addr = server.accept()
    print 'Connection established'

    while connected:
        try:
            data = 'test'
            msg = 'test'
            data = conn.recv(1024)
            print data
            while "\n" in data:
                msg, data = data.split("\n", 1)
                jsonObject = json.loads(msg)
                print jsonObject["speed_up"]

        except ValueError:
            pass

        except KeyboardInterrupt:
            print "test"
            conn.close()
            connected = False
            running = False
            print "close1"
        else:
            if data:
                print data
                running = True
                connected = True
            else:
                conn.close()
                connected = False
                running = True
                print "close2"
    print "end"
    server.shutdown(socket.SHUT_RDWR) 
    server.close()
print "shutdown"
sys.exit()
